version: '3.9'

services:
  server:
    image: ratanachh/inventory
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=Inventory;User=sa;Password=P@SSw0rdGCF078;MultipleActiveResultSets=true"
    ports:
      - "5005:80"
    depends_on:
      - db
    restart: on-failure
    container_name: inventory

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=P@SSw0rdGCF078"
      - "ACCEPT_EULA=Y"
    container_name: mssql
